version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: labs_oop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - labs_oop_db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/labs_oop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      APP_SECURITY_BOOTSTRAP_USERNAME: admin
      APP_SECURITY_BOOTSTRAP_PASSWORD: admin
      APP_SECURITY_BOOTSTRAP_ROLE: ADMIN
    ports:
      - "8080:8080"

volumes:
  labs_oop_db:
